import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my projects',
  projects: [
    {
      id: getId(),
      name: 'confessa',
      url: 'https://confessa-eight.vercel.app/',
      repo: 'https://github.com/kiongosss/confessa',
      img: '/projects/confessa.png',
      year: 2025,
      tags: ['Next.js', 'React', 'Tailwind CSS', 'Anonymous Messaging'],
    },
    {
      id: getId(),
      name: 'copysai',
      url: 'https://copysai.com',
      repo: 'https://github.com/kiongosss/copysai',
      img: '/projects/copysai.png',
      year: 2025,
      tags: ['AI', 'Copywriting', 'SaaS', 'Next.js'],
    },
    {
      id: getId(),
      name: 'webuildaa hunt',
      url: 'https://webuildaa.copysai.com/',
      repo: 'https://github.com/kiongosss/webuildaa-hunt',
      img: '/projects/webuildaa.png',
      year: 2025,
      tags: ['Product Hunt', 'Community', 'Next.js'],
    },
    {
      id: getId(),
      name: 'referz',
      url: 'https://referz.copysai.com/',
      repo: 'https://github.com/kiongosss/referz',
      img: '/projects/referz.png',
      year: 2025,
      tags: ['Referral', 'Marketing', 'SaaS', 'Next.js'],
    },
    {
      id: getId(),
      name: 'tesadeal',
      url: 'https://tesadeal.com/',
      repo: 'https://github.com/kiongosss',
      img: '/projects/tesadeal.png',
      year: 2024,
      tags: ['Next.js', 'React', 'E-commerce'],
    },
    {
      id: getId(),
      name: 'flexcash',
      url: 'https://github.com/kiongosss/flexcash',
      repo: 'https://github.com/kiongosss/flexcash',
      img: '/projects/flexcash.png',
      year: 2023,
      tags: ['React', 'Payments', 'Leaderboard'],
    },
    {
      id: getId(),
      name: 'tinysoko',
      url: 'https://github.com/kiongosss/tinysoko',
      repo: 'https://github.com/kiongosss/tinysoko',
      img: '/projects/tinysoko.png',
      year: 2023,
      tags: ['Marketplace', 'Escrow', 'Social Media'],
    },
    {
      id: getId(),
      name: 'saas landing kit',
      url: 'https://github.com/kiongosss/saas-landing-kit',
      repo: 'https://github.com/kiongosss/saas-landing-kit',
      img: '/projects/saas-landing.png',
      year: 2023,
      tags: ['SaaS', 'Landing Page', 'UI/UX'],
    },
    {
      id: getId(),
      name: 'micro startups acquisitions',
      url: 'https://github.com/kiongosss/micro-startups-acquisitions',
      repo: 'https://github.com/kiongosss/micro-startups-acquisitions',
      img: '/projects/micro-startups.png',
      year: 2023,
      tags: ['Marketplace', 'Startups', 'Acquisitions'],
    },
    {
      id: getId(),
      name: 'countries app',
      url: 'https://countries-app-kv.netlify.app/',
      repo: 'https://github.com/kiongosss/rest-countries-api',
      img: 'https://user-images.githubusercontent.com/68834718/169527851-19fefb2e-e440-411a-a8a1-4767e2c8688a.png',
      year: 2022,
      tags: ['React', 'Sass'],
    },
    {
      id: getId(),
      name: 'rock paper scissors',
      url: 'https://rock-paper-scissors-kv.netlify.app/',
      repo: 'https://github.com/kiongosss/rock-paper-scissors',
      img: 'https://user-images.githubusercontent.com/68834718/162578706-b9e57735-6fbc-4c7b-8243-2a6ba447404e.jpg',
      year: 2022,
      tags: ['React', 'Sass'],
    },
    {
      id: getId(),
      name: 'todo app',
      url: 'https://todo-kv.netlify.app/',
      repo: 'https://github.com/kiongosss/todo-app',
      img: 'https://user-images.githubusercontent.com/68834718/152794002-0e7bc583-084b-4c39-83bb-d82d5dd642b2.png',
      year: 2022,
      tags: ['React', 'Sass', 'JS'],
    },
    {
      id: getId(),
      name: 'weather app',
      url: 'https://weather-kv.netlify.app/',
      repo: 'https://github.com/kiongosss/weather-app',
      img: 'https://user-images.githubusercontent.com/68834718/148419702-491fa08d-e520-4e2f-b219-374ec7118b2b.png',
      year: 2022,
      tags: ['Html', 'sass', 'JS', 'jQuery'],
    },
    {
      id: getId(),
      name: 'blogr landing page',
      url: 'https://blogr-kv.netlify.app/',
      repo: 'https://github.com/kiongosss/blogr-landing-page',
      img: 'https://user-images.githubusercontent.com/68834718/210222542-6455303d-c93e-430b-a5c8-96a431044184.png',
      year: 2021,
      tags: ['html', 'sass', 'JS'],
    },
    {
      id: getId(),
      name: 'natours',
      url: 'https://natours-kv.netlify.app/',
      repo: 'https://github.com/kiongosss/natours',
      img: 'https://user-images.githubusercontent.com/68834718/210223114-b4f64b44-2501-49c9-9fb7-b8e53fe654c6.png',
      year: 2021,
      tags: ['html', 'sass', 'JS'],
    },
    {
      id: getId(),
      name: 'nexter',
      url: 'https://github.com/kiongosss',
      repo: 'https://github.com/kiongosss/nexter',
      img: 'https://user-images.githubusercontent.com/68834718/210224671-5501c5d9-a8d2-4044-a14c-38fb7e46a113.png',
      year: 2021,
      tags: ['html', 'sass'],
    },
    {
      id: getId(),
      name: 'IP address tracker',
      url: 'https://github.com/kiongosss',
      repo: 'https://github.com/kiongosss/ip-address-tracker',
      img: 'https://user-images.githubusercontent.com/68834718/210223386-03bcaa20-e649-4b3d-8709-59e42c6d685a.png',
      year: 2021,
      tags: ['html', 'bootstrap', 'JS'],
    },
    {
      id: getId(),
      name: 'calculator app',
      url: 'https://github.com/kiongosss',
      repo: 'https://github.com/kiongosss/calculator-app/',
      img: 'https://user-images.githubusercontent.com/68834718/210223825-3b68d696-39c6-490c-9433-f315b7efccbd.png',
      year: 2021,
      tags: ['html', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'pig game',
      url: 'https://github.com/kiongosss',
      repo: 'https://github.com/kiongosss/pig-game',
      img: 'https://user-images.githubusercontent.com/68834718/210223527-de7fde7a-244e-4db5-8e33-d561afad6084.png',
      year: 2021,
      tags: ['html', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'bankist marketing',
      url: 'https://github.com/kiongosss',
      repo: 'https://github.com/kiongosss/bankist-marketing',
      img: 'https://user-images.githubusercontent.com/68834718/210225545-989f79c3-cf05-4c53-b48e-b21f373b3734.png',
      year: 2021,
      tags: ['html', 'CSS', 'JS'],
    },
  ],
};



